### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by kohllisti** [aktionskarten/backend#14]
Create Dockercontainers
 workers & backend

**Comment by waschbeer** [comment]
Aim: Generate docker containers with the backend for production and testing.

Problem: Every docker image can run only a single service.
However, we need multiple services: backend, a postgres DB, redis.

Solution: use docker-compose to run multiple containers for each of these services.

Current state (branch `feature/update-docker-container`): 
* there is a docker image for the backend
* no images for postgres and redis yet
* need to update docker-compose file in order to start all of them simultaneously

**Comment by iomn** [comment]
With #37 docker images are supported.
